development:
  adapter: postgresql
  encoding: unicode
  database: townscript_development
  host: localhost
  pool: 5
  username: postgres
  password: 123456

test:
  adapter: postgresql
  encoding: unicode
  database: townscript_test
  host: localhost
  pool: 5
  username: postgres
  password: 123456

production:
  adapter: postgresql
  encoding: unicode
  database: townscript_production
  host: localhost
  pool: 5
  username: postgres
  password: 123456